openapi: 3.1.0
info:
  version: 0.1.0
  title: backend api
servers:
  - url: http://localhost:3000
    description: servidor de desenvolvimento
paths:
  /reservas:
    get:
      responses:
        "200":
          description: lista com as reservas feitas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Reserva"
        "500":
          description: erro ao listar reservas
  /reserva/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 1
          description: id da reserva
      responses:
        "200":
          description: detalhes da reserva
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reserva"
        "400":
          description: reserva não encontrada
        "500":
          description: erro ao buscar reserva
  /reserva:
    post:
      requestBody:
        $ref: "#/components/requestBodies/NovaReservaBody"
      responses:
        "200":
          description: nova reserva feitas
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reserva"
        "500":
          description: erro ao criar reserva
  /destinos:
    get:
      responses:
        "200":
          description: lista com todos os destinos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Destino"
  /destino/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 1
          description: id do destino
      responses:
        "200":
          description: detalhes do destino
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Destino"
        "400":
          description: destino não encontrado
        "500":
          description: erro ao buscar destino
components:
  schemas:
    Reserva:
      type: object
      properties:
        partida:
          type: string
        retorno:
          type: string
        destino:
          $ref: "#/components/schemas/Destino"
        preco:
          type: number
    Destino:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        preco:
          type: integer
  requestBodies:
    NovaReservaBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              id_destino:
                type: integer
              partida:
                type: string
              retorno:
                type: string
          example:
            id_destino: 1
            partida: 2022-01-25T22:31:37.000Z
            retorno: 2022-01-25T22:31:37.000Z
